import React, { useState, useEffect } from 'react';
import { FileText, BrainCircuit, RefreshCw, Printer } from 'lucide-react';
import { fakeBackendAPI } from '../../../services/fakeBackendAPI';

export const AIReportView: React.FC = () => {
    const [riskTrendData, setRiskTrendData] = useState<any[]>([]);
    const [environmentalData, setEnvironmentalData] = useState<any>(null);
    const [fires, setFires] = useState<any[]>([]);

    const [reportContent, setReportContent] = useState('');
    const [displayedContent, setDisplayedContent] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    // Poll for data needed for the report
    useEffect(() => {
        const stopRiskTrend = fakeBackendAPI.startPolling(
            () => fakeBackendAPI.getRiskTrend(),
            5000,
            (data) => setRiskTrendData(data.data || [])
        );

        const stopEnvData = fakeBackendAPI.startPolling(
            () => fakeBackendAPI.getEnvironmentalData(),
            5000,
            (data) => setEnvironmentalData(data)
        );

        const stopFires = fakeBackendAPI.startPolling(
            () => fakeBackendAPI.getFires(),
            5000,
            (data) => setFires(data.fires || [])
        );

        return () => {
            stopRiskTrend();
            stopEnvData();
            stopFires();
        };
    }, []);

    // Generate report content when data is available or requested
    const generateReport = () => {
        setIsGenerating(true);
        setDisplayedContent('');

        const timestamp = new Date().toISOString();
        const activeFiresCount = fires.length;

        let content = `
================================================================================
                    BLAZEGUARD AI - SITUATIONAL ANALYSIS REPORT
================================================================================
REPORT ID: GEN-${Math.floor(Math.random() * 100000)}
TIMESTAMP: ${timestamp}
CLASSIFICATION: CONFIDENTIAL
GENERATED BY: CORTEX-V5 NEURAL ENGINE
================================================================================

1. EXECUTIVE SUMMARY
--------------------
Current operational status indicates ${activeFiresCount > 0 ? 'CRITICAL' : 'NOMINAL'} threat levels. 
Deep learning models have analyzed ${riskTrendData.length} data points correlates with live satellite telemetry.
Primary risk factors identified: ${environmentalData?.windSpeed > 15 ? 'HIGH WIND VELOCITY' : 'THERMAL ANOMALIES'}.

2. GEOSPATIAL SIMILARITY & SPREAD ANALYSIS
------------------------------------------
Analysis of active fire clusters reveals high-dimensional correlations between
ignition vectors and terrain topology.

ACTIVE CLUSTERS:
`;

        fires.forEach((fire) => {
            content += `
[CLUSTER ${fire.id}]
   • LOCATION: Lat ${fire.location[1].toFixed(4)}, Lng ${fire.location[0].toFixed(4)}
   • SEVERITY: ${fire.severity.toUpperCase()} (Confidence: ${(Math.random() * 10 + 90).toFixed(1)}%)
   • SPREAD VECTOR: ${(Math.random() * 360).toFixed(0)}° at ${(Math.random() * 5 + 1).toFixed(1)} km/h
   • TOPOLOGICAL SIMILARITY: ${(Math.random() * 0.5 + 0.4).toFixed(3)} (Matches historical pattern #34-B)
`;
        });

        content += `
3. PREDICTIVE MODELLING
-----------------------
The neural engine predicts a ${(Math.random() * 20 + 70).toFixed(1)}% probability of convergence
between Cluster Alpha and Cluster Beta within the next 4 hours if containment
measures are not expedited.

Recurrent Neural Network (RNN) analysis of wind patterns suggests a westward
expansion into Zone Delta.

4. LOGISTICS OPTIMIZATION
-------------------------
Recommended resource allocation:
   - AERIAL UNIT A-1 -> Sector 4 (Efficiency overlap: 94%)
   - GROUND UNIT G-7 -> Sector 2 (Pathfinding optimized)

================================================================================
END OF REPORT
CONFIDENCE SCORE: 0.98
================================================================================
`;
        setReportContent(content);
    };

    // Initial Generation
    useEffect(() => {
        if (fires.length > 0 && !reportContent) {
            generateReport();
        }
    }, [fires]);

    // Typewriter effect
    useEffect(() => {
        if (reportContent && isGenerating) {
            let i = 0;
            const timer = setInterval(() => {
                setDisplayedContent(reportContent.substring(0, i));
                i += 2; // Character speed
                if (i > reportContent.length) {
                    setDisplayedContent(reportContent); // Ensure full text is shown
                    setIsGenerating(false);
                    clearInterval(timer);
                }
            }, 5);
            return () => clearInterval(timer);
        }
    }, [reportContent, isGenerating]);

    return (
        <div className="p-6 max-w-7xl mx-auto space-y-6 h-[calc(100vh-100px)] flex flex-col">
            <div className="flex justify-between items-center bg-zinc-900 border border-zinc-800 p-6 rounded-2xl">
                <div>
                    <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                        <BrainCircuit className="text-fiery-500" />
                        AI Situation Report
                    </h2>
                    <p className="text-zinc-400 text-sm mt-1">Live generative analysis of operational theater.</p>
                </div>
                <div className="flex gap-3">
                    <button
                        onClick={generateReport}
                        disabled={isGenerating}
                        className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded-lg transition-colors font-medium text-sm border border-zinc-700 disabled:opacity-50"
                    >
                        <RefreshCw size={16} className={isGenerating ? "animate-spin" : ""} />
                        Regenerate
                    </button>
                    <button className="flex items-center gap-2 px-4 py-2 bg-fiery-600 hover:bg-fiery-500 text-white rounded-lg transition-colors font-semibold shadow-lg shadow-fiery-900/20 text-sm">
                        <Printer size={16} />
                        Print Analysis
                    </button>
                </div>
            </div>

            <div className="flex-1 bg-zinc-950 border border-zinc-800 rounded-2xl p-8 overflow-auto font-mono text-sm relative shadow-inner">
                {/* Scanline effect overlay */}
                <div className="absolute inset-0 pointer-events-none bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] z-10 bg-[length:100%_4px,3px_100%]"></div>

                <pre
                    className="whitespace-pre-wrap text-emerald-500/90 leading-relaxed relative z-0"
                    style={{ fontFamily: "'Courier Prime', 'Courier New', monospace", fontSize: '15px', letterSpacing: '0.5px' }}
                >
                    {displayedContent}
                    {isGenerating && <span className="animate-pulse inline-block w-2 h-4 bg-emerald-500 ml-1"></span>}
                </pre>
            </div>
        </div>
    );
};
