import React, { useState, useEffect } from 'react';
import { BrainCircuit, TrendingUp, Wind, Droplets, AlertTriangle, FileText, Thermometer, AlertCircle } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { fakeBackendAPI } from '../../../services/fakeBackendAPI';

export const RiskAnalyticsPanel: React.FC = () => {
    // State for data from backend API
    const [riskTrendData, setRiskTrendData] = useState<any[]>([]);
    const [environmentalData, setEnvironmentalData] = useState<any>(null);
    const [predictions, setPredictions] = useState<any[]>([]);
    const [fires, setFires] = useState<any[]>([]); // Need fires for the report

    // Polling for data updates
    useEffect(() => {
        // Poll for risk trend data
        const stopRiskTrend = fakeBackendAPI.startPolling(
            () => fakeBackendAPI.getRiskTrend(),
            5000,
            (data) => setRiskTrendData(data.data || [])
        );

        // Poll for environmental data
        const stopEnvData = fakeBackendAPI.startPolling(
            () => fakeBackendAPI.getEnvironmentalData(),
            5000,
            (data) => {
                setEnvironmentalData(data);
                // Also update predictions based on env data for "realism"
                const newPredictions = [
                    { type: 'fire', probability: data.temperature > 30 ? 0.8 : 0.4, message: `High potential due to ${data.temperature}°C temps` },
                    { type: 'spread', probability: data.windSpeed > 20 ? 0.9 : 0.5, message: `Wind speed ${data.windSpeed} km / h accelerates spread` }
                ];
                setPredictions(newPredictions);
            }
        );

        // Poll for fires data (for the report)
        const stopFires = fakeBackendAPI.startPolling(
            () => fakeBackendAPI.getFires(),
            5000,
            (data) => setFires(data.fires || [])
        );

        return () => {
            stopRiskTrend();
            stopEnvData();
            stopFires();
        };
    }, []);

    const generateReport = () => {
        const timestamp = new Date().toISOString();
        const activeFiresCount = fires.length;

        let reportContent = `
================================================================================
                    BLAZEGUARD AI - SITUATIONAL ANALYSIS REPORT
================================================================================
REPORT ID: GEN-${Math.floor(Math.random() * 100000)}
TIMESTAMP: ${timestamp}
CLASSIFICATION: CONFIDENTIAL
GENERATED BY: CORTEX-V5 NEURAL ENGINE
================================================================================

1. EXECUTIVE SUMMARY
--------------------
Current operational status indicates ${activeFiresCount > 0 ? 'CRITICAL' : 'NOMINAL'} threat levels.
Deep learning models have analyzed ${riskTrendData.length} data points correlates with live satellite telemetry.
Primary risk factors identified: ${environmentalData?.windSpeed > 15 ? 'HIGH WIND VELOCITY' : 'THERMAL ANOMALIES'}.

2. GEOSPATIAL SIMILARITY & SPREAD ANALYSIS
------------------------------------------
Analysis of active fire clusters reveals high-dimensional correlations between
ignition vectors and terrain topology.

ACTIVE CLUSTERS:
`;

        fires.forEach((fire, idx) => {
            reportContent += `
[CLUSTER ${fire.id}]
   • LOCATION: Lat ${fire.location[1].toFixed(4)}, Lng ${fire.location[0].toFixed(4)}
   • SEVERITY: ${fire.severity.toUpperCase()} (Confidence: ${(Math.random() * 10 + 90).toFixed(1)}%)
   • SPREAD VECTOR: ${(Math.random() * 360).toFixed(0)}° at ${(Math.random() * 5 + 1).toFixed(1)} km/h
   • TOPOLOGICAL SIMILARITY: ${(Math.random() * 0.5 + 0.4).toFixed(3)} (Matches historical pattern #34-B)
`;
        });

        reportContent += `
3. PREDICTIVE MODELLING
-----------------------
The neural engine predicts a ${(Math.random() * 20 + 70).toFixed(1)}% probability of convergence
between Cluster Alpha and Cluster Beta within the next 4 hours if containment
measures are not expedited.

Recurrent Neural Network (RNN) analysis of wind patterns suggests a westward
expansion into Zone Delta.

4. LOGISTICS OPTIMIZATION
-------------------------
Recommended resource allocation:
   - AERIAL UNIT A-1 -> Sector 4 (Efficiency overlap: 94%)
   - GROUND UNIT G-7 -> Sector 2 (Pathfinding optimized)

================================================================================
END OF REPORT
CONFIDENCE SCORE: 0.98
================================================================================
`;

        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `BLAZEGUARD_REPORT_${timestamp.replace(/:/g, '-')}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    // Helper components
    const StatCard = ({ icon: Icon, label, value, trend, color = "fiery" }: any) => (
        <div className="bg-zinc-900 border border-zinc-800 p-4 rounded-xl">
            <div className="flex items-start justify-between">
                <div>
                    <p className="text-zinc-500 text-xs font-medium uppercase tracking-wider">{label}</p>
                    <h3 className="text-2xl font-bold text-zinc-100 mt-1">{value}</h3>
                </div>
                <div className={`p-2 rounded-lg bg-${color}-500/10 text-${color}-500`}>
                    <Icon size={20} />
                </div>
            </div>
            <div className="mt-3 flex items-center gap-2 text-xs">
                {trend && (
                    <span className={`font-medium ${trend.startsWith('+') ? 'text-rose-400' : 'text-fiery-400'}`}>
                        {trend}
                    </span>
                )}
                <span className="text-zinc-600">vs last hour</span>
            </div>
        </div>
    );

    const CustomTooltip = ({ active, payload, label }: any) => {
        if (active && payload && payload.length) {
            return (
                <div className="bg-zinc-900 border border-zinc-700 p-2 rounded shadow-lg">
                    <p className="text-zinc-400 text-xs mb-1">{label}</p>
                    <p className="text-fiery-500 text-sm font-bold">
                        Risk Level: {payload[0].value}
                    </p>
                </div>
            );
        }
        return null;
    };

    return (
        <div className="p-6 max-w-7xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-zinc-100">Risk Analytics & Prediction</h1>
                    <p className="text-zinc-400">Real-time environmental monitoring and fire spread forecasting.</p>
                </div>
                <div className="flex gap-2">
                    <span className="px-3 py-1 bg-fiery-500/10 text-fiery-500 rounded-full text-xs font-bold border border-fiery-500/20">
                        SYSTEM NOMINAL
                    </span>
                    <span className="px-3 py-1 bg-zinc-800 text-zinc-400 rounded-full text-xs font-mono border border-zinc-700">
                        LAST UPDATED: 13:42:05
                    </span>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <StatCard
                    icon={Thermometer}
                    label="Avg Temperature"
                    value={environmentalData?.temperature || 'Loading...'}
                    trend={environmentalData?.temperatureTrend || ''}
                    color="rose"
                />
                <StatCard
                    icon={Wind}
                    label="Wind Speed"
                    value={environmentalData?.windSpeed || 'Loading...'}
                    trend={environmentalData?.windTrend || ''}
                    color="amber"
                />
                <StatCard
                    icon={Droplets}
                    label="Humidity"
                    value={environmentalData?.humidity || 'Loading...'}
                    trend={environmentalData?.humidityTrend || ''}
                    color="rose"
                />
                <StatCard
                    icon={TrendingUp}
                    label="Fire Risk Index"
                    value={environmentalData?.riskIndex || 'Loading...'}
                    trend={environmentalData?.riskLevel || ''}
                    color="rose"
                />
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Main Chart Area */}
                <div className="lg:col-span-2 bg-zinc-900 border border-zinc-800 rounded-2xl p-6 min-h-[400px] flex flex-col">
                    <h3 className="text-zinc-100 font-semibold mb-6 flex items-center gap-2">
                        <TrendingUp size={18} className="text-zinc-500" />
                        Risk Trend Analysis (24h)
                    </h3>
                    <div className="flex-1 w-full min-h-[300px]">
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart
                                data={riskTrendData}
                                margin={{
                                    top: 10,
                                    right: 30,
                                    left: 0,
                                    bottom: 0,
                                }}
                            >
                                <defs>
                                    <linearGradient id="colorRisk" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#f43f5e" stopOpacity={0.3} />
                                        <stop offset="95%" stopColor="#f43f5e" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <CartesianGrid strokeDasharray="3 3" stroke="#27272a" vertical={false} />
                                <XAxis
                                    dataKey="time"
                                    stroke="#71717a"
                                    fontSize={12}
                                    tickLine={false}
                                    axisLine={false}
                                />
                                <YAxis
                                    stroke="#71717a"
                                    fontSize={12}
                                    tickLine={false}
                                    axisLine={false}
                                    domain={[0, 100]}
                                />
                                <Tooltip content={<CustomTooltip />} />
                                <Area
                                    type="monotone"
                                    dataKey="risk"
                                    stroke="#f43f5e"
                                    fillOpacity={1}
                                    fill="url(#colorRisk)"
                                    strokeWidth={3}
                                />
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* AI Insights Panel */}
                <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">
                    <h3 className="text-zinc-100 font-semibold mb-4 flex items-center gap-2">
                        <AlertCircle size={18} className="text-fiery-500" />
                        AI Predictive Insights
                    </h3>
                    <div className="space-y-4">
                        {predictions.length > 0 ? predictions.map((prediction, index) => (
                            <div key={index} className={`p-4 rounded-xl bg-zinc-950/50 border border-zinc-800 border-l-4 ${prediction.severity === 'critical' ? 'border-l-rose-500' :
                                prediction.severity === 'high' ? 'border-l-rose-500' :
                                    prediction.severity === 'medium' ? 'border-l-amber-500' :
                                        'border-l-fiery-500'
                                }`}>
                                <h4 className="text-zinc-200 text-sm font-semibold mb-1 capitalize">{prediction.type} Alert</h4>
                                <p className="text-zinc-400 text-xs leading-relaxed">
                                    {prediction.message}
                                </p>
                            </div>
                        )) : (
                            <div className="p-4 rounded-xl bg-zinc-950/50 border border-zinc-800 text-center">
                                <p className="text-zinc-500 text-sm">Loading predictions...</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};
